### ISSUE TITLE
bug in converting relative address in x64

### ISSUE THREAD

**Issue by imperatoravgust** [x64dbg/XEDParse#1]
when assemble instruction like this 
000007FEF1475C50 | 48 89 1D 11 F9 0F 00     | mov qword ptr ds:[7FEF1575568],rbx     
i get this
000007FEF1475C50 | 48 89 1D 12 F9 0F 00     | mov qword ptr ds:[7FEF1575569],rbx      
so it wrong calculate relative offset of instruction
problem how i see in OperandMem.cpp at 153 line
 LONGLONG newDisp = TranslateRelativeCip(Parse, Operand->Mem.DispVal - 6, true);
Operand->Mem.DispVal - 6  if instruction have size 6 all good , if instruction bigger then 6 we have a error.
So it must be something like that
 LONGLONG newDisp = TranslateRelativeCip(Parse, Operand->Mem.DispVal -Operand->Size, true);

**Comment by mrexodia** [comment]
Yea, this is an issue known for some time. It would require assembling
twice to calculate the instruction size.

**Comment by Nukem9** [comment]
https://github.com/x64dbg/XEDParse/blob/master/XEDParseTest/Tests.h#L88 <-- broken instructions that are tested for this issue.

JMP: 6 bytes (-6)
LEA: 7 bytes (-7)
ADD: 8 bytes (-8)

I know what's wrong. I don't know an easy way to fix it. There are far more instructions than these 3.

**Comment by wk-952** [comment]
@Nukem9
After the first bunch of commits by Herz3h, he did implement a "keep size" option in the assembling window, which calculates the differnce in size between the current instruction - the new instruction.

What I want to say is that, if the problem is the instruction size, may be you can use the function(s) he made to get the the size of the current instruction.

**Comment by mrexodia** [comment]
@wk yes, simply assembling the instruction twice (once to get the size,
once to adjust) is a good solution. Herz3h used the size XEDParse outputs.

**Comment by imperatoravgust** [comment]
now more better but in some instruction have same problem, this for examle
000007FEF18BC878 | C7 05 5E 3B D8 FF 00 00 00 00         | mov dword ptr ds:[7FEF16403E0],0   
get this     
000007FEF18BC878 | C7 05 68 3B D8 FF 00 00 00 00         | mov dword ptr ds:[7FEF16403EA],0       
so how i see, some time it don't calculate size
and problem how i see in dword size operations

**Comment by wk-952** [comment]
`TryEncode64()` is never called when the ptr type is anything other than `qword`
because `TryEncode()` returns true when called by `Translate()`,
so `TryEncode64()` never gets a chance to be called.
But if the ptr type is `qword`, `TryEncode()` returns false and `TryEncode64()` gets called.
