### ISSUE TITLE
error with buildding

### ISSUE THREAD

**Issue by ddkwork** [x64dbg/XEDParse#10]
严重性	代码	说明	项目	文件	行	Suppression State
错误	LNK2019	无法解析的外部符号 __iob_func，该符号在函数 xed_internal_assert 中被引用	XEDParse	C:\Users\Administrator\Desktop\XEDParse-master\libxed_x64.lib(xed-util.obj)	1	

__iob_func  error in vs 2017

**Comment by mrexodia** [comment]
There is no support here. Use vs2013 like the original code.
